[package]
name = "lazyworkflows"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.8"
serde = "1.0.144"
toml = "0.5.9"
dirs = "4.0.0"
fake-useragent = "0.1.3"