FROM ubuntu:latest as dependencies

RUN apt update && apt install -y \
    cargo \
    openssl \
    musl-dev \
    gcc \
    g++ \
    libcurl4-openssl-dev \
    libssl-dev \
    pkg-config

WORKDIR /app
COPY . .

FROM dependencies AS test

ENTRYPOINT [ "cargo", "test" ]